### PR TITLE
[gha] Add workflow to build and publish docs

### PR DESCRIPTION
**Pull request by mgorven**

### CODE REVIEW

**Review by jklein24 — APPROVED** [review]
Awesome :-D

**Review by coreymartin — APPROVED** [review]
We should be able to use Turbo here instead of yarn commands but I'm not 100% sure it will matter without a remote cache, so we can figure this out later. These tasks should be plenty fast at the moment anyways.

**Comment by jklein24** [comment]
> We should be able to use Turbo here instead of yarn commands but I'm not 100% sure it will matter without a remote cache, so we can figure this out later. These tasks should be plenty fast at the moment anyways.

Isn't this just going to use turbo under the hood anyway?

**Comment by coreymartin** [comment]
@jklein24 I think you have to actually use the turbo commands like `yarn turbo docs` and add `docs` as a task to the turbo config.

**Pull request merged**
